spring:
  application:
    name: user-app
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/user_app_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
server:
  port: 8082
url:
  user-login: http://USER-LOGIN
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
