server:
  port: 8082

url:
  user-login: http://localhost:8081

spring:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/user_app_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
