create table role
(
    id   bigserial not null,
    name varchar(255),
    primary key (id)
);

create table app_user
(
    id                 bigserial not null,
    user_credential_id bigserial not null,
    first_name         varchar(255) ,
    last_name          varchar(255) ,
    primary key (id)
);

create table user_roles
(
    user_id int8 not null references app_user (id),
    role_id int8 not null references role (id)
);

--
-- create table app_user
-- (
--     id                 int8 generated by default as identity,
--     first_name         varchar(255),
--     last_name          varchar(255),
--     user_credential_id int8,
--     primary key (id)
-- )
-- create table role
-- (
--     id   int8 generated by default as identity,
--     name varchar(255),
--     primary key (id)
-- )
-- create table user_roles
-- (
--     user_id int8 not null,
--     role_id int8 not null
-- )
-- alter table if exists user_roles
--     add constraint FKrhfovtciq1l558cw6udg0h0d3 foreign key (role_id) references role
-- alter table if exists user_roles
--     add constraint FK6fql8djp64yp4q9b3qeyhr82b foreign key (user_id) references app_user